FROM apache/airflow:2.10.2
USER root 
RUN mkdir /app 
COPY . /app/
WORKDIR /app/ 
RUN pip3 install -r requirements.txt 
ENV AIRFLOW_HOME="/app/airflow"
ENV AIRFLOW_CORE_DAGBAG_IMPORT_TIMEOUT=1000 
ENV AIRFLOW_CORE_ENABLE_XCOM_PICKLING=True 
ENV PYTHONPATH="${PYTHONPATH}:/MLOPS"
RUN chmod 777 start.sh 
RUN apt update -y 
ENTRYPOINT [ "/bin/sh" ]
CMD [ "start.sh" ]